version: '3.1'
services:
  CICD:
    build:
      context: './'
      dockerfile: Dockerfile
    image: cicd-test:v1.0.0
    container_name: CICDTest
    ports:
      - 8088:8080
    deploy:
      resources:
        limits:
          memory: 200M